# Adapted from https://github.com/TYPO3GmbH/blog/blob/master/.github/workflows/ci.yml
name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        typo3: [^8.7, ^9.5, ^10.4]
        php: ['7.2', '7.3', '7.4']
        package: [typo3/cms-core]
        os: [ubuntu-latest]
        exclude:
          - typo3: ^9.5
            php: '7.0'
          - typo3: ^9.5
            php: '7.1'
          - typo3: ^10.4
            php: '7.0'
          - typo3: ^10.4
            php: '7.1'
        include:
          - typo3: ^6.2
            php: '5.6'
            package: typo3/cms
            os: ubuntu-latest
          - typo3: ^7.6
            php: '5.6'
            package: typo3/cms
            os: ubuntu-latest
          - typo3: ^7.6
            php: '7.0'
            package: typo3/cms
            os: ubuntu-latest
          - typo3: ^7.6
            php: '7.1'
            package: typo3/cms
            os: ubuntu-latest
          - typo3: ^7.6
            php: '7.2'
            package: typo3/cms
            os: ubuntu-latest
          - typo3: ^11.0
            php: '7.4'
            package: typo3/cms-core
            os: ubuntu-latest
          - typo3: ^11.0
            php: '8.0'
            package: typo3/cms-core
            os: ubuntu-latest
    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP version ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Environment Check
        run: |
          php --version
          composer --version

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies with ${{ matrix.package }}:${{ matrix.typo3 }}
        run: |
          composer require ${{ matrix.package }}:${{ matrix.typo3 }} --no-progress
          composer require typo3/cms-composer-installers:^1.4 --no-progress
          git checkout composer.json

      - name: php-cs-fixer
        run: composer ci:php:fixer

      - name: Lint PHP
        run: composer ci:php:lint

      - name: Functional Tests
        if: matrix.php > 7.0
        env:
          typo3DatabaseName: test
          typo3DatabaseUsername: root
          typo3DatabasePassword: password
          typo3DatabaseHost: 127.0.0.1
          typo3DatabasePort: ${{ job.services.mysql.ports['3306'] }}
        run: |
          composer ci:tests:functional
