name: CI

on: [pull_request]

jobs:
  cgl:
    name: CGL on TYPO3 v11
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Composer Validate
      run: Build/Scripts/runTests.sh -p 8.1 -t 12 -s composer -e 'validate'

    - name: Composer Install
      run: Build/Scripts/runTests.sh -p 8.1 -t 12 -s composerInstall

    # We have to add composer requirements here as these requirements are
    # not valid for our TYPO3 6.2-10.4 tests
    - name: Composer require testing framework bridge for TYPO3 11/12
      run: Build/Scripts/runTests.sh -p 8.1 -t 12 -s composer -e 'require sbuerk/typo3-cmscomposerinstallers-testingframework-bridge:^0.1'

    - name: Composer require TYPO3 coding standards
      run: Build/Scripts/runTests.sh -p 8.1 -t 12 -s composer -e 'require typo3/coding-standards:^0.6.1'

    - name: Composer require php-cs-fixer
      run: Build/Scripts/runTests.sh -p 8.1 -t 12 -s composer -e 'require friendsofphp/php-cs-fixer:^3.14.0'

    - name: Lint PHP
      run: Build/Scripts/runTests.sh -p 8.1 -t 12 -s lint

    - name: Validate code against CGL
      run: PHP_CS_FIXER_IGNORE_ENV=1 Build/Scripts/runTests.sh -p 8.1 -t 12 -s cgl -n

  tests:
    name: Test on TYPO3 v11
    needs: cgl
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        php: ['7.4', '8.0', '8.1']

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Composer Install
      run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 12 -s composerInstall

    # We have to add composer requirements here as these requirements are
    # not valid for our TYPO3 6.2-10.4 tests
    - name: Composer require phpunit in version 9.6
      run: Build/Scripts/runTests.sh -p 8.1 -t 12 -s composer -e 'require phpunit/phpunit:^9.6'

    - name: Composer require TYPO3 testing framework
      run: Build/Scripts/runTests.sh -p 8.1 -t 12 -s composer -e 'require typo3/testing-framework:~7.0@dev'

    - name: Composer require testing framework bridge for TYPO3 11/12
      run: Build/Scripts/runTests.sh -p 8.1 -t 12 -s composer -e 'require sbuerk/typo3-cmscomposerinstallers-testingframework-bridge:^0.1'

    - name: Unit tests
      run: Build/Scripts/runTests.sh -p ${{ matrix.php }} -t 12 -s unit
